### ISSUE TITLE
[Feature Request] Keep session

### ISSUE THREAD

**Issue by palexdev** [ndg63276/smartathome#8]
Would it be possible for the "Keep me logged in" option to be permanent, or at least to last longer?
I have a random password, so it's quite cumbersome to re-login every time

**Comment by ndg63276** [comment]
The length of the login session is controlled by the individual service and the API they provide. When the token they provide expires, the site asks you to login again. The server cannot store your password, that would be hideously insecure.

Your browser could store your password, but this is usually done by a password manager rather than some sort of cookie.

**Comment by palexdev** [comment]
Ah I see
I thought it was the web app controlling the cookie
Thanks for your work nonetheless!
